[features]
seeds = false
[programs.localnet]
mycalculatordapp = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/atoo35/.config/solana/id.json"

[scripts]
test = "yarn run mocha -p -t 1000000 tests/**/*.js"
